### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Starou** [Starou/django-stachoutils#1]
## AdminExtra / dump
- [ ] manage m2m (and infinite recursion) 
- [ ] handle object order 
- [x] virer lowerize() qui était utilisé dans Publish dans import Cadrimmo pour le nom court des programmes. Checker avant que plus utilisé.
- [x] supprimer le `shortcuts.json_response()` car built-in depuis Django-1.7.
- [ ] views/generic.py#100 : Faire le ménage dans `get_filters` car les filtres fermés sont gérés en js.
